### ISSUE TITLE
how to solve this?

### ISSUE THREAD

**Issue by marlenexxx** [noaione/yuu#10]
C:\Windows\system32>yuu
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python37-32\Scripts\yuu.exe\__main__.py", line 5, in <module>
  File "c:\program files (x86)\python37-32\lib\site-packages\yuu\command.py", line 8, in <module>
    from .common import __version__, isUserAdmin, res_data, runAsAdmin
ImportError: cannot import name 'runAsAdmin' from 'yuu.common' (c:\program files (x86)\python37-32\lib\site-packages\yuu\common.py)

**Comment by noaione** [comment]
1. Go to your python installation folder
2. Go to `lib -> site-packages -> yuu`
3. Open `command.py` with any text editor
4. Edit line 8 from this `from .common import __version__, isUserAdmin, res_data, runAsAdmin` `from .common import __version__, isUserAdmin, res_data`

I forget to do some cleanup, will push new version with some other fixes in a minute

**Comment by noaione** [comment]
Pushed, update it using `pip install -U yuu==0.2.3`

**Comment by marlenexxx** [comment]
thank you it work..

also did i do wrong?
```
C:\MAIN>yuu download -p https://183.76.154.184:8080 https://ds-vod-abematv.akamaized.net/program/90-1248_s1_p1001/playlist.m3u8?t=Du2VfqcfYq7ye8wq6cJRUdgm3Ax2bqs7utumyUAgNYDg5ATFA2saWK4QFZj8wYoiKye8wKUY5dhxUgMa22Vy28FxLTKTYfZL5ozyL1aQc2Zg3Hjv4YEh551nmyYprL&enc=clear&dt=pc_chrome&ccf=0&kg=737
[INFO] Starting yuu v0.2.3...
[INFO] Testing proxy
[INFO] Fetching user token
[INFO] Parsing webpage
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python37-32\Scripts\yuu.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python37-32\lib\site-packages\yuu\command.py", line 181, in main
    cli()
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\yuu\command.py", line 122, in main_downloader
    outputtitle, m3u8link = webparse(input, res, sesi, verbose)
  File "c:\program files (x86)\python37-32\lib\site-packages\yuu\parser.py", line 316, in webparse
    title = jsdata['series']['title']
KeyError: 'series'
'enc' is not recognized as an internal or external command,
operable program or batch file.
'dt' is not recognized as an internal or external command,
operable program or batch file.
'ccf' is not recognized as an internal or external command,
operable program or batch file.
'kg' is not recognized as an internal or external command,
operable program or batch file.```
