### ISSUE TITLE
KeyError: 'series'

### ISSUE THREAD

**Issue by noaione** [noaione/yuu#5]
```
Traceback (most recent call last):
  File "/home/memencoder/.local/bin/yuu", line 11, in <module>
    sys.exit(main())
  File "/home/memencoder/.local/lib/python3.5/site-packages/yuu/command.py", line 73, in main
    outputtitle, m3u8link = webparse(args.input, args.res, sesi, args.verbose)
  File "/home/memencoder/.local/lib/python3.5/site-packages/yuu/parser.py", line 233, in webparse
    title = jsdata['series']['title']
KeyError: 'series'
```

I will look on this later, probably Abema changing something on the API

**Comment by noaione** [comment]
Someone that I know actually got KeyError problem when he try to fetch the Video key.

There's 2 possibilities:
1. Proxy problem
2. API changes

**Comment by noaione** [comment]
Proxy problem, no changes were made to the API
