### ISSUE TITLE
 ERROR: Complete output from command python setup.py egg_info:

### ISSUE THREAD

**Issue by rafa020804** [noaione/yuu#7]
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rafael\AppData\Local\Temp\pip-install-vprr2fqc\yuu\setup.py", line 2, in <module>
        from yuu.common import __version__
      File "C:\Users\rafael\AppData\Local\Temp\pip-install-vprr2fqc\yuu\yuu\__init__.py", line 2, in <module>
        from .parser import *
      File "C:\Users\rafael\AppData\Local\Temp\pip-install-vprr2fqc\yuu\yuu\parser.py", line 7, in <module>
        import m3u8 as M3U8
    ModuleNotFoundError: No module named 'm3u8'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\rafael\AppData\Local\Temp\pip-install-vprr2fqc\yuu\

**Comment by noaione** [comment]
Try to install everything one-by-one

`pip install -U requests[socks] m3u8 tqdm pycryptodome`

**Comment by rafa020804** [comment]
It worked thanks!
edit: now i am getting this message:
ERROR] Problem occured
reason: ("read error: Error([('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')])",)

and were the file goes after the download?

**Comment by rafa020804** [comment]
I am sorry but where the file goes after I finish downloading?
